### ISSUE TITLE
Could you add a way to change the pronouns displayed ?

### ISSUE THREAD

**Issue by v4rl1** [splaudpanther/SimpleUserPrononouns#1]
My community isn't english speaking, and we have a different set of pronouns that wouldn't translate so great, do you think there is a way we could change the pronouns ?

**Comment by captpanther** [comment]
Thank you for the suggestion, however currently only English Pronouns are supported, I will look into ways to support multi-language pronouns and add them to the future roadmap.

**Comment by v4rl1** [comment]
Thank you very much !
